[project]
name = "analyse_trajectory"
version = "1.0.0"
description = "Borophene trajectory analysis and classification"
requires-python = ">=3.12"
dependencies = [
    "ase==3.26.0",
    "matplotlib>=3.10.9",
    "numpy>=1.23.5,<2.0.0",
    "pandas==2.3.3",
    'tqdm>=4.66.1',
    'dscribe==2.1.2',
    'opencv-python==4.10.0.82'
]

[tool.uv]
package = false
