#!/bin/bash
#SBATCH -J active_training
#SBATCH -A theochem
#SBATCH -p tc1
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -w node27
#SBATCH -t UNLIMITED
#SBATCH -e ./active_training.err
#SBATCH -o ./active_training.out

export OMP_NUM_THREADS=1
export PYTHONPATH=$PYTHONPATH:$HOME/Boro_ML/bin
export VASP_PP_PATH=$HOME/bin/vasp
PYTHONBIN=/softs/anaconda3/bin/python3

PAT=.
cp $HOME/Boro_ML/bin/active_learning/active_training.py $PAT
cd $PAT
$PYTHONBIN active_training.py

